"""Curated CBSA panel for the Manufacturing Opportunity Index.

Pillar scores (0-100) are a POC calibration of public-data dimensions:
manufacturing intensity, freight access, labor, industrial real estate,
and growth. Cluster scores capture known OEM/fab/3PL presence.

This is not a live Census/BLS pull. The schema is built so those feeds
can replace the static pillars later without changing the scoring engine.
"""

METROS: list[dict] = [
    {
        "cbsa": "26900",
        "short": "Indianapolis",
        "name": "Indianapolis-Carmel-Anderson, IN",
        "state": "IN",
        "region": "Midwest",
        "lat": 39.7684,
        "lon": -86.1581,
        "population": 2_111_000,
        "manufacturing": 82,
        "logistics": 91,
        "labor": 78,
        "warehouse": 87,
        "growth": 84,
        "automotive": 74,
        "warehousing": 91,
        "food_manufacturing": 72,
        "battery_manufacturing": 58,
        "semiconductors": 38,
        "distribution_centers": 93,
        "materials_handling": 95,
        "tagline": "Crossroads of America — inland port without a coast.",
        "highlights": [
            "I-65/I-70/I-74 confluence and CSX/NS rail",
            "National 3PL and e-commerce DC concentration",
            "Competitive industrial land versus coastal gateways",
        ],
    },
    {
        "cbsa": "18140",
        "short": "Columbus OH",
        "name": "Columbus, OH",
        "state": "OH",
        "region": "Midwest",
        "lat": 39.9612,
        "lon": -82.9988,
        "population": 2_180_000,
        "manufacturing": 86,
        "logistics": 89,
        "labor": 80,
        "warehouse": 91,
        "growth": 88,
        "automotive": 72,
        "warehousing": 93,
        "food_manufacturing": 70,
        "battery_manufacturing": 76,
        "semiconductors": 84,
        "distribution_centers": 90,
        "materials_handling": 96,
        "tagline": "Intel-scale power plus Rickenbacker freight.",
        "highlights": [
            "Intel Ohio fab investment and supplier follow-on",
            "Rickenbacker inland port and air cargo",
            "Deep big-box warehouse inventory east and south of the city",
        ],
    },
    {
        "cbsa": "19100",
        "short": "Dallas",
        "name": "Dallas-Fort Worth-Arlington, TX",
        "state": "TX",
        "region": "South",
        "lat": 32.7767,
        "lon": -96.7970,
        "population": 7_940_000,
        "manufacturing": 76,
        "logistics": 94,
        "labor": 85,
        "warehouse": 93,
        "growth": 91,
        "automotive": 62,
        "warehousing": 95,
        "food_manufacturing": 78,
        "battery_manufacturing": 64,
        "semiconductors": 82,
        "distribution_centers": 96,
        "materials_handling": 89,
        "tagline": "The Sun Belt's freight and fulfillment capital.",
        "highlights": [
            "DFW air cargo, UP/BNSF intermodal, and I-35/I-20/I-45",
            "Texas Instruments and a growing semiconductor corridor",
            "Large-scale speculative industrial pipeline",
        ],
    },
    {
        "cbsa": "12060",
        "short": "Atlanta",
        "name": "Atlanta-Sandy Springs-Roswell, GA",
        "state": "GA",
        "region": "South",
        "lat": 33.7490,
        "lon": -84.3880,
        "population": 6_307_000,
        "manufacturing": 71,
        "logistics": 95,
        "labor": 82,
        "warehouse": 94,
        "growth": 87,
        "automotive": 68,
        "warehousing": 94,
        "food_manufacturing": 74,
        "battery_manufacturing": 70,
        "semiconductors": 48,
        "distribution_centers": 97,
        "materials_handling": 90,
        "tagline": "Hartsfield cargo plus the Southeast's DC machine.",
        "highlights": [
            "World's busiest passenger hub with heavy belly cargo",
            "I-75/I-85/I-20 coverage of the Southeast population",
            "Proximity to Savannah auto/battery investments",
        ],
    },
    {
        "cbsa": "19820",
        "short": "Detroit",
        "name": "Detroit-Warren-Dearborn, MI",
        "state": "MI",
        "region": "Midwest",
        "lat": 42.3314,
        "lon": -83.0458,
        "population": 4_365_000,
        "manufacturing": 95,
        "logistics": 80,
        "labor": 76,
        "warehouse": 78,
        "growth": 72,
        "automotive": 98,
        "warehousing": 70,
        "food_manufacturing": 62,
        "battery_manufacturing": 88,
        "semiconductors": 42,
        "distribution_centers": 68,
        "materials_handling": 86,
        "tagline": "Still the densest auto supplier ecosystem in North America.",
        "highlights": [
            "OEM headquarters, tooling, and Tier-1 density",
            "Ultium and EV retooling across SE Michigan",
            "Canada-US freight via Ambassador Bridge and tunnel",
        ],
    },
    {
        "cbsa": "34980",
        "short": "Nashville",
        "name": "Nashville-Davidson-Murfreesboro-Franklin, TN",
        "state": "TN",
        "region": "South",
        "lat": 36.1627,
        "lon": -86.7816,
        "population": 2_102_000,
        "manufacturing": 84,
        "logistics": 85,
        "labor": 82,
        "warehouse": 86,
        "growth": 90,
        "automotive": 90,
        "warehousing": 84,
        "food_manufacturing": 68,
        "battery_manufacturing": 86,
        "semiconductors": 40,
        "distribution_centers": 83,
        "materials_handling": 70,
        "tagline": "Nissan-GM-Ford triangle with fast population growth.",
        "highlights": [
            "Nissan Smyrna, GM Spring Hill, and Bridgestone",
            "Ford BlueOval / SK corridor within a one-day haul",
            "No state income tax and strong in-migration",
        ],
    },
    {
        "cbsa": "32820",
        "short": "Memphis",
        "name": "Memphis, TN-MS-AR",
        "state": "TN",
        "region": "South",
        "lat": 35.1495,
        "lon": -90.0490,
        "population": 1_337_000,
        "manufacturing": 68,
        "logistics": 97,
        "labor": 80,
        "warehouse": 92,
        "growth": 74,
        "automotive": 52,
        "warehousing": 90,
        "food_manufacturing": 76,
        "battery_manufacturing": 48,
        "semiconductors": 22,
        "distribution_centers": 99,
        "materials_handling": 87,
        "tagline": "FedEx SuperHub — overnight America from one ramp.",
        "highlights": [
            "World's largest air-cargo operation",
            "Mississippi River, BNSF/UP/CN/CSX, and I-40/I-55",
            "Food, pharma, and high-velocity parcel DCs",
        ],
    },
    {
        "cbsa": "31140",
        "short": "Louisville",
        "name": "Louisville/Jefferson County, KY-IN",
        "state": "KY",
        "region": "South",
        "lat": 38.2527,
        "lon": -85.7585,
        "population": 1_365_000,
        "manufacturing": 80,
        "logistics": 93,
        "labor": 79,
        "warehouse": 88,
        "growth": 80,
        "automotive": 78,
        "warehousing": 88,
        "food_manufacturing": 74,
        "battery_manufacturing": 84,
        "semiconductors": 28,
        "distribution_centers": 92,
        "materials_handling": 88,
        "tagline": "UPS Worldport plus Ford and GE Appliance manufacturing.",
        "highlights": [
            "UPS Worldport air-cargo gravity",
            "Ford Kentucky Truck and BlueOval SK in the state",
            "Appliance, whiskey, and food processing base",
        ],
    },
    {
        "cbsa": "17140",
        "short": "Cincinnati",
        "name": "Cincinnati, OH-KY-IN",
        "state": "OH",
        "region": "Midwest",
        "lat": 39.1031,
        "lon": -84.5120,
        "population": 2_265_000,
        "manufacturing": 81,
        "logistics": 86,
        "labor": 80,
        "warehouse": 85,
        "growth": 78,
        "automotive": 70,
        "warehousing": 83,
        "food_manufacturing": 88,
        "battery_manufacturing": 54,
        "semiconductors": 34,
        "distribution_centers": 82,
        "materials_handling": 78,
        "tagline": "CPG headquarters city with I-75 manufacturing spine.",
        "highlights": [
            "P&G, Kroger, and a deep food/CPG supplier base",
            "I-75 auto corridor between Detroit and the South",
            "CVG Amazon Air hub",
        ],
    },
    {
        "cbsa": "28140",
        "short": "Kansas City",
        "name": "Kansas City, MO-KS",
        "state": "MO",
        "region": "Midwest",
        "lat": 39.0997,
        "lon": -94.5786,
        "population": 2_210_000,
        "manufacturing": 77,
        "logistics": 92,
        "labor": 83,
        "warehouse": 90,
        "growth": 81,
        "automotive": 76,
        "warehousing": 91,
        "food_manufacturing": 82,
        "battery_manufacturing": 50,
        "semiconductors": 30,
        "distribution_centers": 90,
        "materials_handling": 76,
        "tagline": "Rail capital of the Plains with Ford and food processing.",
        "highlights": [
            "One of the largest US rail hubs (BNSF/UP/KCS)",
            "Ford Claycomo and a growing EV supplier presence",
            "Central two-day truck coverage of the Lower 48",
        ],
    },
    {
        "cbsa": "16980",
        "short": "Chicago",
        "name": "Chicago-Naperville-Elgin, IL-IN-WI",
        "state": "IL",
        "region": "Midwest",
        "lat": 41.8781,
        "lon": -87.6298,
        "population": 9_262_000,
        "manufacturing": 83,
        "logistics": 94,
        "labor": 70,
        "warehouse": 86,
        "growth": 68,
        "automotive": 64,
        "warehousing": 88,
        "food_manufacturing": 90,
        "battery_manufacturing": 46,
        "semiconductors": 40,
        "distribution_centers": 88,
        "materials_handling": 92,
        "tagline": "The original intermodal machine — high capability, higher cost.",
        "highlights": [
            "Nation's largest rail interchange and O'Hare cargo",
            "Food processing, packaging, and cold-storage density",
            "Wage and tax drag versus Indiana/Wisconsin peers",
        ],
    },
    {
        "cbsa": "26420",
        "short": "Houston",
        "name": "Houston-Pasadena-The Woodlands, TX",
        "state": "TX",
        "region": "South",
        "lat": 29.7604,
        "lon": -95.3698,
        "population": 7_340_000,
        "manufacturing": 84,
        "logistics": 93,
        "labor": 80,
        "warehouse": 90,
        "growth": 86,
        "automotive": 40,
        "warehousing": 88,
        "food_manufacturing": 72,
        "battery_manufacturing": 66,
        "semiconductors": 44,
        "distribution_centers": 86,
        "materials_handling": 82,
        "tagline": "Port, chemicals, and energy-adjacent manufacturing at scale.",
        "highlights": [
            "Port Houston container and bulk leadership",
            "Gulf Coast chemicals, polymers, and process manufacturing",
            "Energy-transition equipment and industrial power",
        ],
    },
    {
        "cbsa": "38060",
        "short": "Phoenix",
        "name": "Phoenix-Mesa-Chandler, AZ",
        "state": "AZ",
        "region": "West",
        "lat": 33.4484,
        "lon": -112.0740,
        "population": 5_070_000,
        "manufacturing": 74,
        "logistics": 86,
        "labor": 84,
        "warehouse": 88,
        "growth": 93,
        "automotive": 48,
        "warehousing": 87,
        "food_manufacturing": 60,
        "battery_manufacturing": 72,
        "semiconductors": 95,
        "distribution_centers": 86,
        "materials_handling": 62,
        "tagline": "TSMC + Intel — the West's CHIPS gravity well.",
        "highlights": [
            "TSMC Arizona and Intel Ocotillo/Chandler",
            "I-10 West Coast-to-Texas freight lane",
            "Fast population growth and large-site desert land",
        ],
    },
    {
        "cbsa": "12420",
        "short": "Austin",
        "name": "Austin-Round Rock-San Marcos, TX",
        "state": "TX",
        "region": "South",
        "lat": 30.2672,
        "lon": -97.7431,
        "population": 2_473_000,
        "manufacturing": 75,
        "logistics": 78,
        "labor": 80,
        "warehouse": 80,
        "growth": 94,
        "automotive": 70,
        "warehousing": 76,
        "food_manufacturing": 52,
        "battery_manufacturing": 74,
        "semiconductors": 96,
        "distribution_centers": 74,
        "materials_handling": 52,
        "tagline": "Samsung, Tesla, and a STEM labor magnet.",
        "highlights": [
            "Samsung Taylor fab and a long electronics history",
            "Tesla Giga Texas vehicle and energy production",
            "Tight industrial land and rising labor competition",
        ],
    },
    {
        "cbsa": "16740",
        "short": "Charlotte",
        "name": "Charlotte-Concord-Gastonia, NC-SC",
        "state": "NC",
        "region": "South",
        "lat": 35.2271,
        "lon": -80.8431,
        "population": 2_805_000,
        "manufacturing": 76,
        "logistics": 88,
        "labor": 82,
        "warehouse": 87,
        "growth": 88,
        "automotive": 64,
        "warehousing": 86,
        "food_manufacturing": 70,
        "battery_manufacturing": 58,
        "semiconductors": 46,
        "distribution_centers": 88,
        "materials_handling": 75,
        "tagline": "Carolinas freight hub between the Piedmont and the ports.",
        "highlights": [
            "I-77/I-85 coverage of the Carolinas manufacturing belt",
            "Charlotte Douglas air cargo and banking capital",
            "Access to Charleston and Wilmington ports",
        ],
    },
    {
        "cbsa": "24860",
        "short": "Greenville SC",
        "name": "Greenville-Anderson-Greer, SC",
        "state": "SC",
        "region": "South",
        "lat": 34.8526,
        "lon": -82.3940,
        "population": 975_000,
        "manufacturing": 92,
        "logistics": 78,
        "labor": 81,
        "warehouse": 80,
        "growth": 83,
        "automotive": 94,
        "warehousing": 74,
        "food_manufacturing": 58,
        "battery_manufacturing": 72,
        "semiconductors": 36,
        "distribution_centers": 70,
        "materials_handling": 83,
        "tagline": "BMW Spartanburg and the Upstate supplier park model.",
        "highlights": [
            "BMW's largest plant globally is next door",
            "Michelin, Bosch, and a dense German supplier base",
            "I-85 auto alley from Atlanta to Greensboro",
        ],
    },
    {
        "cbsa": "16700",
        "short": "Charleston",
        "name": "Charleston-North Charleston, SC",
        "state": "SC",
        "region": "South",
        "lat": 32.7765,
        "lon": -79.9311,
        "population": 849_000,
        "manufacturing": 83,
        "logistics": 90,
        "labor": 76,
        "warehouse": 82,
        "growth": 85,
        "automotive": 82,
        "warehousing": 80,
        "food_manufacturing": 54,
        "battery_manufacturing": 68,
        "semiconductors": 34,
        "distribution_centers": 78,
        "materials_handling": 64,
        "tagline": "Deep-water port with Volvo, Mercedes van, and Boeing.",
        "highlights": [
            "South Carolina Ports Authority growth",
            "Volvo Cars and Mercedes-Benz vans",
            "Boeing 787 and a rising industrial corridor",
        ],
    },
    {
        "cbsa": "42340",
        "short": "Savannah",
        "name": "Savannah, GA",
        "state": "GA",
        "region": "South",
        "lat": 32.0809,
        "lon": -81.0912,
        "population": 431_000,
        "manufacturing": 82,
        "logistics": 92,
        "labor": 78,
        "warehouse": 84,
        "growth": 86,
        "automotive": 88,
        "warehousing": 82,
        "food_manufacturing": 56,
        "battery_manufacturing": 94,
        "semiconductors": 24,
        "distribution_centers": 80,
        "materials_handling": 84,
        "tagline": "Hyundai Metaplant and a surging South Atlantic port.",
        "highlights": [
            "Hyundai Metaplant and SK battery co-location",
            "Port of Savannah container growth",
            "Still-available industrial land versus Atlanta",
        ],
    },
    {
        "cbsa": "13820",
        "short": "Birmingham",
        "name": "Birmingham, AL",
        "state": "AL",
        "region": "South",
        "lat": 33.5186,
        "lon": -86.8104,
        "population": 1_178_000,
        "manufacturing": 80,
        "logistics": 76,
        "labor": 81,
        "warehouse": 74,
        "growth": 76,
        "automotive": 84,
        "warehousing": 70,
        "food_manufacturing": 64,
        "battery_manufacturing": 62,
        "semiconductors": 22,
        "distribution_centers": 68,
        "materials_handling": 58,
        "tagline": "Steel, Mercedes, Honda, and a still-underpriced labor market.",
        "highlights": [
            "Mercedes Vance and Honda Lincoln within the state",
            "Historic metals and heavy manufacturing base",
            "I-20/I-65 inland position",
        ],
    },
    {
        "cbsa": "26620",
        "short": "Huntsville",
        "name": "Huntsville, AL",
        "state": "AL",
        "region": "South",
        "lat": 34.7304,
        "lon": -86.5861,
        "population": 514_000,
        "manufacturing": 90,
        "logistics": 72,
        "labor": 86,
        "warehouse": 74,
        "growth": 89,
        "automotive": 70,
        "warehousing": 68,
        "food_manufacturing": 48,
        "battery_manufacturing": 64,
        "semiconductors": 58,
        "distribution_centers": 62,
        "materials_handling": 55,
        "tagline": "Mazda Toyota, aviation, and the highest STEM density in Alabama.",
        "highlights": [
            "Mazda Toyota Manufacturing",
            "Redstone, NASA, and a deep engineering labor pool",
            "Toyota battery and EV-adjacent investment in the state",
        ],
    },
    {
        "cbsa": "16860",
        "short": "Chattanooga",
        "name": "Chattanooga, TN-GA",
        "state": "TN",
        "region": "South",
        "lat": 35.0456,
        "lon": -85.3097,
        "population": 573_000,
        "manufacturing": 86,
        "logistics": 80,
        "labor": 82,
        "warehouse": 78,
        "growth": 80,
        "automotive": 90,
        "warehousing": 74,
        "food_manufacturing": 60,
        "battery_manufacturing": 80,
        "semiconductors": 26,
        "distribution_centers": 72,
        "materials_handling": 60,
        "tagline": "Volkswagen's US base on the I-75 auto spine.",
        "highlights": [
            "VW Chattanooga and Scout Motors nearby",
            "I-75 between Detroit, Kentucky, and Atlanta",
            "Tennessee Valley industrial power",
        ],
    },
    {
        "cbsa": "45780",
        "short": "Toledo",
        "name": "Toledo, OH",
        "state": "OH",
        "region": "Midwest",
        "lat": 41.6528,
        "lon": -83.5379,
        "population": 641_000,
        "manufacturing": 88,
        "logistics": 83,
        "labor": 78,
        "warehouse": 76,
        "growth": 70,
        "automotive": 92,
        "warehousing": 72,
        "food_manufacturing": 66,
        "battery_manufacturing": 86,
        "semiconductors": 24,
        "distribution_centers": 68,
        "materials_handling": 72,
        "tagline": "Jeep, glass, and Great Lakes freight at a lower cost.",
        "highlights": [
            "Stellantis Toledo Assembly and supplier parks",
            "Port of Toledo and I-75/I-80/I-90 access",
            "Glass, chemicals, and EV materials adjacency",
        ],
    },
    {
        "cbsa": "24340",
        "short": "Grand Rapids",
        "name": "Grand Rapids-Wyoming-Kentwood, MI",
        "state": "MI",
        "region": "Midwest",
        "lat": 42.9634,
        "lon": -85.6681,
        "population": 1_093_000,
        "manufacturing": 90,
        "logistics": 76,
        "labor": 83,
        "warehouse": 78,
        "growth": 77,
        "automotive": 80,
        "warehousing": 72,
        "food_manufacturing": 86,
        "battery_manufacturing": 58,
        "semiconductors": 30,
        "distribution_centers": 70,
        "materials_handling": 85,
        "tagline": "Office furniture, food, and auto suppliers — a quiet factory city.",
        "highlights": [
            "One of the densest manufacturing employment shares in the US",
            "Food processing and cold storage along the lakeshore",
            "Auto interiors and furniture supply chain",
        ],
    },
    {
        "cbsa": "33340",
        "short": "Milwaukee",
        "name": "Milwaukee-Waukesha, WI",
        "state": "WI",
        "region": "Midwest",
        "lat": 43.0389,
        "lon": -87.9065,
        "population": 1_574_000,
        "manufacturing": 91,
        "logistics": 80,
        "labor": 79,
        "warehouse": 77,
        "growth": 72,
        "automotive": 62,
        "warehousing": 72,
        "food_manufacturing": 84,
        "battery_manufacturing": 50,
        "semiconductors": 36,
        "distribution_centers": 70,
        "materials_handling": 65,
        "tagline": "Machine tools, food, and a still-intact industrial culture.",
        "highlights": [
            "High manufacturing location quotient",
            "Food, beverage, and industrial equipment",
            "Port of Milwaukee and I-94 Chicago corridor",
        ],
    },
    {
        "cbsa": "33460",
        "short": "Minneapolis",
        "name": "Minneapolis-St. Paul-Bloomington, MN-WI",
        "state": "MN",
        "region": "Midwest",
        "lat": 44.9778,
        "lon": -93.2650,
        "population": 3_690_000,
        "manufacturing": 78,
        "logistics": 82,
        "labor": 84,
        "warehouse": 80,
        "growth": 78,
        "automotive": 36,
        "warehousing": 78,
        "food_manufacturing": 86,
        "battery_manufacturing": 40,
        "semiconductors": 48,
        "distribution_centers": 80,
        "materials_handling": 63,
        "tagline": "Med-tech and food CPG with a high-skill labor bench.",
        "highlights": [
            "General Mills, Cargill, and a deep food-science cluster",
            "Medical devices and precision manufacturing",
            "MSP cargo and Upper Midwest distribution",
        ],
    },
    {
        "cbsa": "41180",
        "short": "St. Louis",
        "name": "St. Louis, MO-IL",
        "state": "MO",
        "region": "Midwest",
        "lat": 38.6270,
        "lon": -90.1994,
        "population": 2_803_000,
        "manufacturing": 79,
        "logistics": 85,
        "labor": 80,
        "warehouse": 82,
        "growth": 72,
        "automotive": 74,
        "warehousing": 80,
        "food_manufacturing": 80,
        "battery_manufacturing": 52,
        "semiconductors": 28,
        "distribution_centers": 81,
        "materials_handling": 70,
        "tagline": "Mississippi confluence, Boeing, and a rebuilt auto footprint.",
        "highlights": [
            "I-44/I-55/I-64/I-70 and barge access",
            "GM Wentzville and a historic auto/food base",
            "National geospatial and defense manufacturing",
        ],
    },
    {
        "cbsa": "39900",
        "short": "Reno",
        "name": "Reno, NV",
        "state": "NV",
        "region": "West",
        "lat": 39.5296,
        "lon": -119.8138,
        "population": 511_000,
        "manufacturing": 80,
        "logistics": 84,
        "labor": 80,
        "warehouse": 88,
        "growth": 86,
        "automotive": 58,
        "warehousing": 90,
        "food_manufacturing": 50,
        "battery_manufacturing": 93,
        "semiconductors": 42,
        "distribution_centers": 88,
        "materials_handling": 60,
        "tagline": "Tesla-Panasonic gigafactory and the California overflow warehouse.",
        "highlights": [
            "Gigafactory Nevada cells and energy storage",
            "Tahoe-Reno Industrial Center mega-sites",
            "West Coast fulfillment without California tax/land cost",
        ],
    },
    {
        "cbsa": "38900",
        "short": "Portland",
        "name": "Portland-Vancouver-Hillsboro, OR-WA",
        "state": "OR",
        "region": "West",
        "lat": 45.5152,
        "lon": -122.6784,
        "population": 2_511_000,
        "manufacturing": 84,
        "logistics": 78,
        "labor": 76,
        "warehouse": 72,
        "growth": 74,
        "automotive": 22,
        "warehousing": 68,
        "food_manufacturing": 64,
        "battery_manufacturing": 40,
        "semiconductors": 92,
        "distribution_centers": 66,
        "materials_handling": 80,
        "tagline": "Intel Hillsboro and a Pacific Northwest precision cluster.",
        "highlights": [
            "Intel's long-standing Oregon campus",
            "Port of Portland and Columbia River freight",
            "Land and housing constraints versus Sun Belt fab sites",
        ],
    },
    {
        "cbsa": "14260",
        "short": "Boise",
        "name": "Boise City, ID",
        "state": "ID",
        "region": "West",
        "lat": 43.6150,
        "lon": -116.2023,
        "population": 811_000,
        "manufacturing": 78,
        "logistics": 70,
        "labor": 83,
        "warehouse": 76,
        "growth": 90,
        "automotive": 18,
        "warehousing": 74,
        "food_manufacturing": 62,
        "battery_manufacturing": 36,
        "semiconductors": 93,
        "distribution_centers": 72,
        "materials_handling": 42,
        "tagline": "Micron's hometown with fast in-migration and cheap power.",
        "highlights": [
            "Micron memory manufacturing and R&D",
            "Competitive electricity and land versus coastal fab markets",
            "Food processing (potatoes, dairy) alongside tech",
        ],
    },
    {
        "cbsa": "41620",
        "short": "Salt Lake City",
        "name": "Salt Lake City-Murray, UT",
        "state": "UT",
        "region": "West",
        "lat": 40.7608,
        "lon": -111.8910,
        "population": 1_263_000,
        "manufacturing": 74,
        "logistics": 82,
        "labor": 86,
        "warehouse": 84,
        "growth": 88,
        "automotive": 28,
        "warehousing": 84,
        "food_manufacturing": 58,
        "battery_manufacturing": 44,
        "semiconductors": 68,
        "distribution_centers": 85,
        "materials_handling": 56,
        "tagline": "West-interior DC hub with a young, growing workforce.",
        "highlights": [
            "I-15 inland empire for West Coast overflow",
            "Young labor force and strong in-migration",
            "Semiconductor materials and data-center adjacency",
        ],
    },
    {
        "cbsa": "19740",
        "short": "Denver",
        "name": "Denver-Aurora-Centennial, CO",
        "state": "CO",
        "region": "West",
        "lat": 39.7392,
        "lon": -104.9903,
        "population": 2_986_000,
        "manufacturing": 70,
        "logistics": 84,
        "labor": 78,
        "warehouse": 82,
        "growth": 86,
        "automotive": 32,
        "warehousing": 82,
        "food_manufacturing": 66,
        "battery_manufacturing": 42,
        "semiconductors": 50,
        "distribution_centers": 84,
        "materials_handling": 58,
        "tagline": "Front Range distribution for the Mountain West.",
        "highlights": [
            "I-70/I-25 coverage of the Rockies and Plains",
            "DIA cargo and a growing industrial northeast corridor",
            "Higher wages and housing costs than Midwest peers",
        ],
    },
    {
        "cbsa": "39580",
        "short": "Raleigh",
        "name": "Raleigh-Cary, NC",
        "state": "NC",
        "region": "South",
        "lat": 35.7796,
        "lon": -78.6382,
        "population": 1_509_000,
        "manufacturing": 72,
        "logistics": 80,
        "labor": 88,
        "warehouse": 82,
        "growth": 91,
        "automotive": 34,
        "warehousing": 80,
        "food_manufacturing": 58,
        "battery_manufacturing": 48,
        "semiconductors": 80,
        "distribution_centers": 81,
        "materials_handling": 64,
        "tagline": "Research Triangle STEM plus fast warehouse growth.",
        "highlights": [
            "Research Triangle universities and technician supply",
            "Wolfspeed and a compounding electronics cluster",
            "I-40 corridor to Greensboro manufacturing",
        ],
    },
    {
        "cbsa": "40060",
        "short": "Richmond",
        "name": "Richmond, VA",
        "state": "VA",
        "region": "South",
        "lat": 37.5407,
        "lon": -77.4360,
        "population": 1_339_000,
        "manufacturing": 74,
        "logistics": 84,
        "labor": 81,
        "warehouse": 86,
        "growth": 82,
        "automotive": 40,
        "warehousing": 85,
        "food_manufacturing": 70,
        "battery_manufacturing": 46,
        "semiconductors": 54,
        "distribution_centers": 86,
        "materials_handling": 62,
        "tagline": "I-95 Mid-Atlantic DC belt with a port one hour away.",
        "highlights": [
            "I-95/I-64 between the Northeast and the Carolinas",
            "Port of Virginia adjacency",
            "Food, tobacco heritage, and data-center overlay",
        ],
    },
    {
        "cbsa": "27260",
        "short": "Jacksonville",
        "name": "Jacksonville, FL",
        "state": "FL",
        "region": "South",
        "lat": 30.3322,
        "lon": -81.6557,
        "population": 1_703_000,
        "manufacturing": 68,
        "logistics": 88,
        "labor": 82,
        "warehouse": 86,
        "growth": 88,
        "automotive": 36,
        "warehousing": 86,
        "food_manufacturing": 64,
        "battery_manufacturing": 40,
        "semiconductors": 26,
        "distribution_centers": 88,
        "materials_handling": 66,
        "tagline": "First Coast port and the Southeast's Florida gateway.",
        "highlights": [
            "JAXPORT and CSX headquarters freight culture",
            "I-10/I-95 confluence",
            "Lower industrial cost than South Florida",
        ],
    },
    {
        "cbsa": "45300",
        "short": "Tampa",
        "name": "Tampa-St. Petersburg-Clearwater, FL",
        "state": "FL",
        "region": "South",
        "lat": 27.9506,
        "lon": -82.4572,
        "population": 3_342_000,
        "manufacturing": 64,
        "logistics": 82,
        "labor": 80,
        "warehouse": 84,
        "growth": 87,
        "automotive": 24,
        "warehousing": 83,
        "food_manufacturing": 68,
        "battery_manufacturing": 32,
        "semiconductors": 28,
        "distribution_centers": 84,
        "materials_handling": 60,
        "tagline": "Florida West Coast consumption with a growing industrial east.",
        "highlights": [
            "Port Tampa Bay bulk and emerging containers",
            "I-4 corridor to Orlando fulfillment",
            "Insurance, defense, and food distribution",
        ],
    },
    {
        "cbsa": "40140",
        "short": "Inland Empire",
        "name": "Riverside-San Bernardino-Ontario, CA",
        "state": "CA",
        "region": "West",
        "lat": 34.0633,
        "lon": -117.6509,
        "population": 4_688_000,
        "manufacturing": 70,
        "logistics": 93,
        "labor": 68,
        "warehouse": 96,
        "growth": 80,
        "automotive": 30,
        "warehousing": 98,
        "food_manufacturing": 66,
        "battery_manufacturing": 38,
        "semiconductors": 32,
        "distribution_centers": 95,
        "materials_handling": 78,
        "tagline": "The nation's densest warehouse market — and its most constrained.",
        "highlights": [
            "SoCal port-driven import warehousing",
            "Unmatched big-box inventory depth",
            "High rents, labor tightness, and CEQA friction",
        ],
    },
    {
        "cbsa": "31080",
        "short": "Los Angeles",
        "name": "Los Angeles-Long Beach-Anaheim, CA",
        "state": "CA",
        "region": "West",
        "lat": 34.0522,
        "lon": -118.2437,
        "population": 12_872_000,
        "manufacturing": 72,
        "logistics": 90,
        "labor": 58,
        "warehouse": 70,
        "growth": 66,
        "automotive": 34,
        "warehousing": 78,
        "food_manufacturing": 74,
        "battery_manufacturing": 40,
        "semiconductors": 46,
        "distribution_centers": 80,
        "materials_handling": 70,
        "tagline": "San Pedro Bay ports — unmatched gateway, expensive everything else.",
        "highlights": [
            "Busiest US container complex",
            "Apparel, aerospace, and food manufacturing remnants",
            "Land, labor, and power costs push new plants inland",
        ],
    },
    {
        "cbsa": "10900",
        "short": "Allentown",
        "name": "Allentown-Bethlehem-Easton, PA-NJ",
        "state": "PA",
        "region": "Northeast",
        "lat": 40.6084,
        "lon": -75.4902,
        "population": 865_000,
        "manufacturing": 74,
        "logistics": 90,
        "labor": 77,
        "warehouse": 94,
        "growth": 78,
        "automotive": 36,
        "warehousing": 95,
        "food_manufacturing": 72,
        "battery_manufacturing": 42,
        "semiconductors": 30,
        "distribution_centers": 94,
        "materials_handling": 72,
        "tagline": "I-78 warehouse alley covering New York and Philadelphia.",
        "highlights": [
            "Lehigh Valley mega-warehouse cluster",
            "Overnight coverage of the Northeast megalopolis",
            "Former steel valley with industrial land reuse",
        ],
    },
    {
        "cbsa": "25420",
        "short": "Harrisburg",
        "name": "Harrisburg-Carlisle, PA",
        "state": "PA",
        "region": "Northeast",
        "lat": 40.2732,
        "lon": -76.8867,
        "population": 591_000,
        "manufacturing": 70,
        "logistics": 89,
        "labor": 80,
        "warehouse": 91,
        "growth": 76,
        "automotive": 32,
        "warehousing": 92,
        "food_manufacturing": 74,
        "battery_manufacturing": 34,
        "semiconductors": 24,
        "distribution_centers": 91,
        "materials_handling": 70,
        "tagline": "Pennsylvania Turnpike / I-81 inland port for the Northeast.",
        "highlights": [
            "I-81/I-83/I-76 freight confluence",
            "Major grocery and 3PL DC concentration",
            "Lower cost than Northern New Jersey",
        ],
    },
    {
        "cbsa": "38300",
        "short": "Pittsburgh",
        "name": "Pittsburgh, PA",
        "state": "PA",
        "region": "Northeast",
        "lat": 40.4406,
        "lon": -79.9959,
        "population": 2_370_000,
        "manufacturing": 80,
        "logistics": 78,
        "labor": 82,
        "warehouse": 74,
        "growth": 70,
        "automotive": 48,
        "warehousing": 68,
        "food_manufacturing": 62,
        "battery_manufacturing": 56,
        "semiconductors": 52,
        "distribution_centers": 66,
        "materials_handling": 58,
        "tagline": "Advanced manufacturing and robotics on a metals foundation.",
        "highlights": [
            "Carnegie Mellon robotics and industrial AI",
            "Energy, metals, and process manufacturing",
            "Rivers plus I-76/I-79 but hillier industrial sites",
        ],
    },
    {
        "cbsa": "17460",
        "short": "Cleveland",
        "name": "Cleveland-Elyria, OH",
        "state": "OH",
        "region": "Midwest",
        "lat": 41.4993,
        "lon": -81.6944,
        "population": 2_162_000,
        "manufacturing": 86,
        "logistics": 82,
        "labor": 78,
        "warehouse": 76,
        "growth": 68,
        "automotive": 78,
        "warehousing": 72,
        "food_manufacturing": 70,
        "battery_manufacturing": 60,
        "semiconductors": 32,
        "distribution_centers": 70,
        "materials_handling": 73,
        "tagline": "Polymers, metals, and auto suppliers on Lake Erie.",
        "highlights": [
            "High manufacturing intensity and tooling trades",
            "Port of Cleveland and I-80/I-90",
            "Slower population growth than Columbus",
        ],
    },
    {
        "cbsa": "15380",
        "short": "Buffalo",
        "name": "Buffalo-Cheektowaga, NY",
        "state": "NY",
        "region": "Northeast",
        "lat": 42.8864,
        "lon": -78.8784,
        "population": 1_162_000,
        "manufacturing": 78,
        "logistics": 80,
        "labor": 80,
        "warehouse": 76,
        "growth": 72,
        "automotive": 58,
        "warehousing": 74,
        "food_manufacturing": 76,
        "battery_manufacturing": 70,
        "semiconductors": 54,
        "distribution_centers": 72,
        "materials_handling": 56,
        "tagline": "Cheap power, Canada trade, and a rebuilding factory base.",
        "highlights": [
            "Low-cost hydropower from Niagara",
            "Peace Bridge trade with Ontario auto plants",
            "Food processing and EV-adjacent manufacturing",
        ],
    },
    {
        "cbsa": "10580",
        "short": "Albany",
        "name": "Albany-Schenectady-Troy, NY",
        "state": "NY",
        "region": "Northeast",
        "lat": 42.6526,
        "lon": -73.7562,
        "population": 905_000,
        "manufacturing": 82,
        "logistics": 74,
        "labor": 80,
        "warehouse": 70,
        "growth": 76,
        "automotive": 24,
        "warehousing": 66,
        "food_manufacturing": 52,
        "battery_manufacturing": 48,
        "semiconductors": 90,
        "distribution_centers": 64,
        "materials_handling": 68,
        "tagline": "GlobalFoundries Malta and the original US nano-cluster.",
        "highlights": [
            "GlobalFoundries Fab 8 and NY CREATES",
            "IBM heritage and technician pipeline",
            "Micron Syracuse-area investment within the region",
        ],
    },
    {
        "cbsa": "36540",
        "short": "Omaha",
        "name": "Omaha, NE-IA",
        "state": "NE",
        "region": "Midwest",
        "lat": 41.2565,
        "lon": -95.9345,
        "population": 983_000,
        "manufacturing": 74,
        "logistics": 84,
        "labor": 86,
        "warehouse": 80,
        "growth": 78,
        "automotive": 28,
        "warehousing": 78,
        "food_manufacturing": 94,
        "battery_manufacturing": 30,
        "semiconductors": 22,
        "distribution_centers": 80,
        "materials_handling": 54,
        "tagline": "Protein, grain, and Union Pacific — the food-system metro.",
        "highlights": [
            "UP headquarters and a central rail position",
            "Beef, grain, and cold-chain processing",
            "Low unemployment and competitive industrial wages",
        ],
    },
    {
        "cbsa": "19780",
        "short": "Des Moines",
        "name": "Des Moines-West Des Moines, IA",
        "state": "IA",
        "region": "Midwest",
        "lat": 41.5868,
        "lon": -93.6250,
        "population": 722_000,
        "manufacturing": 72,
        "logistics": 80,
        "labor": 87,
        "warehouse": 78,
        "growth": 80,
        "automotive": 22,
        "warehousing": 76,
        "food_manufacturing": 92,
        "battery_manufacturing": 28,
        "semiconductors": 20,
        "distribution_centers": 76,
        "materials_handling": 48,
        "tagline": "Corn-belt processing with a stable, high-participation workforce.",
        "highlights": [
            "Agricultural inbound and food manufacturing",
            "I-35/I-80 crossroads",
            "Insurance capital with a practical industrial culture",
        ],
    },
    {
        "cbsa": "36420",
        "short": "Oklahoma City",
        "name": "Oklahoma City, OK",
        "state": "OK",
        "region": "South",
        "lat": 35.4676,
        "lon": -97.5164,
        "population": 1_481_000,
        "manufacturing": 72,
        "logistics": 84,
        "labor": 85,
        "warehouse": 84,
        "growth": 83,
        "automotive": 46,
        "warehousing": 84,
        "food_manufacturing": 70,
        "battery_manufacturing": 44,
        "semiconductors": 26,
        "distribution_centers": 84,
        "materials_handling": 58,
        "tagline": "I-35/I-40 inland hub with energy and food manufacturing.",
        "highlights": [
            "Central I-35 NAFTA/USMCA freight lane",
            "Energy equipment and food processing",
            "Low occupancy cost versus Dallas",
        ],
    },
    {
        "cbsa": "46140",
        "short": "Tulsa",
        "name": "Tulsa, OK",
        "state": "OK",
        "region": "South",
        "lat": 36.1540,
        "lon": -95.9928,
        "population": 1_023_000,
        "manufacturing": 78,
        "logistics": 80,
        "labor": 83,
        "warehouse": 80,
        "growth": 78,
        "automotive": 42,
        "warehousing": 78,
        "food_manufacturing": 68,
        "battery_manufacturing": 40,
        "semiconductors": 24,
        "distribution_centers": 76,
        "materials_handling": 52,
        "tagline": "Aerospace, energy equipment, and a working industrial river.",
        "highlights": [
            "American Airlines maintenance and aerospace suppliers",
            "Port of Catoosa inland waterway",
            "Lower cost alternative to DFW for plants",
        ],
    },
    {
        "cbsa": "41700",
        "short": "San Antonio",
        "name": "San Antonio-New Braunfels, TX",
        "state": "TX",
        "region": "South",
        "lat": 29.4241,
        "lon": -98.4936,
        "population": 2_655_000,
        "manufacturing": 74,
        "logistics": 82,
        "labor": 84,
        "warehouse": 84,
        "growth": 86,
        "automotive": 80,
        "warehousing": 82,
        "food_manufacturing": 72,
        "battery_manufacturing": 58,
        "semiconductors": 46,
        "distribution_centers": 82,
        "materials_handling": 54,
        "tagline": "Toyota plus military logistics on the I-35 South Texas lane.",
        "highlights": [
            "Toyota Tundra/Sequoia assembly",
            "I-35 to Mexico and I-10 east-west",
            "Lower land and wage costs than Austin",
        ],
    },
    {
        "cbsa": "41940",
        "short": "San Jose",
        "name": "San Jose-Sunnyvale-Santa Clara, CA",
        "state": "CA",
        "region": "West",
        "lat": 37.3382,
        "lon": -121.8863,
        "population": 1_958_000,
        "manufacturing": 86,
        "logistics": 70,
        "labor": 62,
        "warehouse": 52,
        "growth": 74,
        "automotive": 28,
        "warehousing": 48,
        "food_manufacturing": 40,
        "battery_manufacturing": 50,
        "semiconductors": 99,
        "distribution_centers": 46,
        "materials_handling": 38,
        "tagline": "The design and equipment capital — rarely the expansion site.",
        "highlights": [
            "Unmatched semiconductor design and equipment cluster",
            "Highest industrial occupancy costs in the panel",
            "New wafer capacity typically lands in AZ, TX, OH, NY, ID",
        ],
    },
    {
        "cbsa": "41740",
        "short": "San Diego",
        "name": "San Diego-Chula Vista-Carlsbad, CA",
        "state": "CA",
        "region": "West",
        "lat": 32.7157,
        "lon": -117.1611,
        "population": 3_286_000,
        "manufacturing": 72,
        "logistics": 76,
        "labor": 64,
        "warehouse": 68,
        "growth": 76,
        "automotive": 26,
        "warehousing": 64,
        "food_manufacturing": 58,
        "battery_manufacturing": 44,
        "semiconductors": 70,
        "distribution_centers": 62,
        "materials_handling": 44,
        "tagline": "Defense, biotech, and a Cali-Baja manufacturing option.",
        "highlights": [
            "Qualcomm heritage and a semiconductor design bench",
            "Otay Mesa / Tijuana maquila adjacency",
            "Constrained industrial land",
        ],
    },
    {
        "cbsa": "47900",
        "short": "Washington DC",
        "name": "Washington-Arlington-Alexandria, DC-VA-MD-WV",
        "state": "VA",
        "region": "South",
        "lat": 38.9072,
        "lon": -77.0369,
        "population": 6_304_000,
        "manufacturing": 52,
        "logistics": 78,
        "labor": 72,
        "warehouse": 74,
        "growth": 80,
        "automotive": 18,
        "warehousing": 72,
        "food_manufacturing": 48,
        "battery_manufacturing": 28,
        "semiconductors": 44,
        "distribution_centers": 76,
        "materials_handling": 48,
        "tagline": "A consumption market with Northern Virginia data-center overlay.",
        "highlights": [
            "I-95 Mid-Atlantic distribution",
            "Data-center construction driving electrical-equipment demand",
            "High wages and limited heavy-industrial sites",
        ],
    },
    {
        "cbsa": "37980",
        "short": "Philadelphia",
        "name": "Philadelphia-Camden-Wilmington, PA-NJ-DE-MD",
        "state": "PA",
        "region": "Northeast",
        "lat": 39.9526,
        "lon": -75.1652,
        "population": 6_246_000,
        "manufacturing": 74,
        "logistics": 86,
        "labor": 72,
        "warehouse": 80,
        "growth": 70,
        "automotive": 34,
        "warehousing": 82,
        "food_manufacturing": 76,
        "battery_manufacturing": 40,
        "semiconductors": 42,
        "distribution_centers": 84,
        "materials_handling": 68,
        "tagline": "Port, pharma, and the I-95 warehouse corridor.",
        "highlights": [
            "Port of Philadelphia and South Jersey industrial",
            "Life-sciences manufacturing and food",
            "Lehigh Valley and Harrisburg as overflow",
        ],
    },
    {
        "cbsa": "14460",
        "short": "Boston",
        "name": "Boston-Cambridge-Newton, MA-NH",
        "state": "MA",
        "region": "Northeast",
        "lat": 42.3601,
        "lon": -71.0589,
        "population": 4_900_000,
        "manufacturing": 70,
        "logistics": 72,
        "labor": 68,
        "warehouse": 60,
        "growth": 74,
        "automotive": 16,
        "warehousing": 56,
        "food_manufacturing": 54,
        "battery_manufacturing": 46,
        "semiconductors": 72,
        "distribution_centers": 58,
        "materials_handling": 50,
        "tagline": "Life science and instrumentation — not a bulk industrial play.",
        "highlights": [
            "Biomanufacturing and precision instruments",
            "Strong universities, tight industrial land",
            "New Hampshire overflow for warehousing",
        ],
    },
    {
        "cbsa": "42660",
        "short": "Seattle",
        "name": "Seattle-Tacoma-Bellevue, WA",
        "state": "WA",
        "region": "West",
        "lat": 47.6062,
        "lon": -122.3321,
        "population": 4_034_000,
        "manufacturing": 80,
        "logistics": 86,
        "labor": 64,
        "warehouse": 74,
        "growth": 78,
        "automotive": 22,
        "warehousing": 76,
        "food_manufacturing": 62,
        "battery_manufacturing": 42,
        "semiconductors": 58,
        "distribution_centers": 78,
        "materials_handling": 58,
        "tagline": "Boeing, ports, and a high-cost Northwest gateway.",
        "highlights": [
            "Ports of Seattle and Tacoma",
            "Aerospace manufacturing density",
            "Wage and housing costs limit new bulk plants",
        ],
    },
    {
        "cbsa": "23060",
        "short": "Fort Wayne",
        "name": "Fort Wayne, IN",
        "state": "IN",
        "region": "Midwest",
        "lat": 41.0793,
        "lon": -85.1394,
        "population": 423_000,
        "manufacturing": 88,
        "logistics": 80,
        "labor": 84,
        "warehouse": 80,
        "growth": 76,
        "automotive": 86,
        "warehousing": 78,
        "food_manufacturing": 64,
        "battery_manufacturing": 62,
        "semiconductors": 22,
        "distribution_centers": 74,
        "materials_handling": 74,
        "tagline": "Northeast Indiana auto suppliers at Midwest wages.",
        "highlights": [
            "GM, BAE, and a dense auto-parts base",
            "I-69 between Indianapolis and Detroit",
            "Very competitive industrial occupancy costs",
        ],
    },
    {
        "cbsa": "19380",
        "short": "Dayton",
        "name": "Dayton-Kettering-Beavercreek, OH",
        "state": "OH",
        "region": "Midwest",
        "lat": 39.7589,
        "lon": -84.1916,
        "population": 814_000,
        "manufacturing": 84,
        "logistics": 82,
        "labor": 80,
        "warehouse": 80,
        "growth": 74,
        "automotive": 80,
        "warehousing": 80,
        "food_manufacturing": 62,
        "battery_manufacturing": 58,
        "semiconductors": 30,
        "distribution_centers": 78,
        "materials_handling": 94,
        "tagline": "I-70/I-75 crossroads with defense and auto manufacturing.",
        "highlights": [
            "Wright-Patt defense manufacturing overlay",
            "Honda Marysville / East Liberty within the labor shed",
            "Strong 3PL presence on I-70",
        ],
    },
    {
        "cbsa": "24660",
        "short": "Greensboro",
        "name": "Greensboro-High Point, NC",
        "state": "NC",
        "region": "South",
        "lat": 36.0726,
        "lon": -79.7920,
        "population": 789_000,
        "manufacturing": 82,
        "logistics": 84,
        "labor": 81,
        "warehouse": 84,
        "growth": 78,
        "automotive": 72,
        "warehousing": 84,
        "food_manufacturing": 66,
        "battery_manufacturing": 54,
        "semiconductors": 34,
        "distribution_centers": 83,
        "materials_handling": 74,
        "tagline": "Piedmont Triad — furniture heritage, now freight and auto.",
        "highlights": [
            "FedEx Greensboro hub and I-40/I-85",
            "Volvo trucks and auto suppliers",
            "Lower cost than Raleigh for industrial users",
        ],
    },
    {
        "cbsa": "22220",
        "short": "NW Arkansas",
        "name": "Fayetteville-Springdale-Rogers, AR",
        "state": "AR",
        "region": "South",
        "lat": 36.0822,
        "lon": -94.1719,
        "population": 576_000,
        "manufacturing": 76,
        "logistics": 88,
        "labor": 82,
        "warehouse": 86,
        "growth": 90,
        "automotive": 24,
        "warehousing": 88,
        "food_manufacturing": 90,
        "battery_manufacturing": 26,
        "semiconductors": 18,
        "distribution_centers": 92,
        "materials_handling": 62,
        "tagline": "Walmart gravity — suppliers, food, and DCs follow HQ.",
        "highlights": [
            "Walmart, Tyson, and J.B. Hunt headquarters effect",
            "Supplier campus and food manufacturing density",
            "Fast growth and a unique retail logistics cluster",
        ],
    },
    {
        "cbsa": "47260",
        "short": "Norfolk",
        "name": "Virginia Beach-Chesapeake-Norfolk, VA-NC",
        "state": "VA",
        "region": "South",
        "lat": 36.8508,
        "lon": -76.2859,
        "population": 1_803_000,
        "manufacturing": 72,
        "logistics": 91,
        "labor": 76,
        "warehouse": 80,
        "growth": 76,
        "automotive": 28,
        "warehousing": 80,
        "food_manufacturing": 58,
        "battery_manufacturing": 36,
        "semiconductors": 32,
        "distribution_centers": 82,
        "materials_handling": 58,
        "tagline": "Port of Virginia — the East Coast's deep-draft play.",
        "highlights": [
            "Deepest East Coast commercial channels",
            "Shipbuilding and defense industrial base",
            "Hampton Roads industrial land constraints",
        ],
    },
    {
        "cbsa": "36740",
        "short": "Orlando",
        "name": "Orlando-Kissimmee-Sanford, FL",
        "state": "FL",
        "region": "South",
        "lat": 28.5383,
        "lon": -81.3792,
        "population": 2_818_000,
        "manufacturing": 58,
        "logistics": 80,
        "labor": 78,
        "warehouse": 84,
        "growth": 90,
        "automotive": 20,
        "warehousing": 84,
        "food_manufacturing": 56,
        "battery_manufacturing": 28,
        "semiconductors": 30,
        "distribution_centers": 86,
        "materials_handling": 55,
        "tagline": "Florida consumption growth with I-4 industrial infill.",
        "highlights": [
            "Rapid household growth driving DC demand",
            "I-4 between Tampa and the Space Coast",
            "Limited heavy manufacturing tradition",
        ],
    },
    {
        "cbsa": "44700",
        "short": "Stockton",
        "name": "Stockton-Lodi, CA",
        "state": "CA",
        "region": "West",
        "lat": 37.9577,
        "lon": -121.2908,
        "population": 791_000,
        "manufacturing": 68,
        "logistics": 88,
        "labor": 72,
        "warehouse": 93,
        "growth": 76,
        "automotive": 22,
        "warehousing": 94,
        "food_manufacturing": 84,
        "battery_manufacturing": 30,
        "semiconductors": 20,
        "distribution_centers": 90,
        "materials_handling": 68,
        "tagline": "Northern California's inland warehouse and food-processing belt.",
        "highlights": [
            "Altamont Pass overflow from the Bay Area",
            "Ag inbound and food manufacturing",
            "Port of Stockton bulk and project cargo",
        ],
    },
    {
        "cbsa": "12580",
        "short": "Baltimore",
        "name": "Baltimore-Columbia-Towson, MD",
        "state": "MD",
        "region": "South",
        "lat": 39.2904,
        "lon": -76.6122,
        "population": 2_838_000,
        "manufacturing": 70,
        "logistics": 88,
        "labor": 74,
        "warehouse": 80,
        "growth": 72,
        "automotive": 42,
        "warehousing": 80,
        "food_manufacturing": 64,
        "battery_manufacturing": 38,
        "semiconductors": 36,
        "distribution_centers": 82,
        "materials_handling": 67,
        "tagline": "Port of Baltimore autos and Mid-Atlantic distribution.",
        "highlights": [
            "Roll-on/roll-off auto import leadership",
            "I-95 between Philly and DC",
            "Spark and Amazon-scale warehouses in the counties",
        ],
    },
    {
        "cbsa": "35300",
        "short": "New Haven",
        "name": "New Haven-Milford, CT",
        "state": "CT",
        "region": "Northeast",
        "lat": 41.3083,
        "lon": -72.9279,
        "population": 864_000,
        "manufacturing": 72,
        "logistics": 74,
        "labor": 70,
        "warehouse": 68,
        "growth": 66,
        "automotive": 20,
        "warehousing": 66,
        "food_manufacturing": 58,
        "battery_manufacturing": 34,
        "semiconductors": 40,
        "distribution_centers": 68,
        "materials_handling": 48,
        "tagline": "Precision manufacturing squeezed by Northeast costs.",
        "highlights": [
            "Legacy precision and medical manufacturing",
            "I-95 coastal freight",
            "Limited large-site industrial land",
        ],
    },
    {
        "cbsa": "35380",
        "short": "New Orleans",
        "name": "New Orleans-Metairie, LA",
        "state": "LA",
        "region": "South",
        "lat": 29.9511,
        "lon": -90.0715,
        "population": 1_270_000,
        "manufacturing": 76,
        "logistics": 90,
        "labor": 74,
        "warehouse": 72,
        "growth": 70,
        "automotive": 24,
        "warehousing": 70,
        "food_manufacturing": 72,
        "battery_manufacturing": 48,
        "semiconductors": 18,
        "distribution_centers": 68,
        "materials_handling": 50,
        "tagline": "Mississippi mouth — chemicals, bulk, and energy equipment.",
        "highlights": [
            "Port of South Louisiana / NOLA bulk leadership",
            "Gulf petrochemicals and shipbuilding",
            "Industrial sites along the river, not big-box DCs",
        ],
    },
    {
        "cbsa": "29820",
        "short": "Las Vegas",
        "name": "Las Vegas-Henderson-North Las Vegas, NV",
        "state": "NV",
        "region": "West",
        "lat": 36.1699,
        "lon": -115.1398,
        "population": 2_337_000,
        "manufacturing": 58,
        "logistics": 80,
        "labor": 78,
        "warehouse": 86,
        "growth": 84,
        "automotive": 22,
        "warehousing": 86,
        "food_manufacturing": 48,
        "battery_manufacturing": 40,
        "semiconductors": 28,
        "distribution_centers": 84,
        "materials_handling": 46,
        "tagline": "SoCal overflow warehousing with no inventory tax.",
        "highlights": [
            "I-15 to Southern California",
            "No inventory tax and 24/7 industrial culture",
            "Limited heavy manufacturing water/power for fabs",
        ],
    },
    {
        "cbsa": "46060",
        "short": "Tucson",
        "name": "Tucson, AZ",
        "state": "AZ",
        "region": "West",
        "lat": 32.2226,
        "lon": -110.9747,
        "population": 1_068_000,
        "manufacturing": 74,
        "logistics": 72,
        "labor": 80,
        "warehouse": 76,
        "growth": 82,
        "automotive": 26,
        "warehousing": 74,
        "food_manufacturing": 50,
        "battery_manufacturing": 42,
        "semiconductors": 76,
        "distribution_centers": 70,
        "materials_handling": 40,
        "tagline": "Raytheon, optics, and a lower-cost Phoenix alternative.",
        "highlights": [
            "Defense and optics manufacturing",
            "University of Arizona STEM pipeline",
            "I-10 but thinner industrial inventory than Phoenix",
        ],
    },
    {
        "cbsa": "10740",
        "short": "Albuquerque",
        "name": "Albuquerque, NM",
        "state": "NM",
        "region": "West",
        "lat": 35.0844,
        "lon": -106.6504,
        "population": 918_000,
        "manufacturing": 76,
        "logistics": 74,
        "labor": 80,
        "warehouse": 72,
        "growth": 76,
        "automotive": 20,
        "warehousing": 70,
        "food_manufacturing": 48,
        "battery_manufacturing": 38,
        "semiconductors": 82,
        "distribution_centers": 68,
        "materials_handling": 38,
        "tagline": "Intel Rio Rancho and national-lab adjacent manufacturing.",
        "highlights": [
            "Intel New Mexico campus",
            "Sandia / Los Alamos talent spillover",
            "I-40/I-25 but a thinner 3PL market",
        ],
    },
    {
        "cbsa": "21340",
        "short": "El Paso",
        "name": "El Paso, TX",
        "state": "TX",
        "region": "South",
        "lat": 31.7619,
        "lon": -106.4850,
        "population": 870_000,
        "manufacturing": 78,
        "logistics": 86,
        "labor": 84,
        "warehouse": 82,
        "growth": 80,
        "automotive": 70,
        "warehousing": 82,
        "food_manufacturing": 58,
        "battery_manufacturing": 52,
        "semiconductors": 34,
        "distribution_centers": 80,
        "materials_handling": 48,
        "tagline": "US-Mexico production twin with Juárez maquila depth.",
        "highlights": [
            "One of the largest binational manufacturing complexes",
            "Auto electronics, medical devices, and appliances",
            "I-10 and UP/BNSF border freight",
        ],
    },
    {
        "cbsa": "17900",
        "short": "Columbia SC",
        "name": "Columbia, SC",
        "state": "SC",
        "region": "South",
        "lat": 34.0007,
        "lon": -81.0348,
        "population": 847_000,
        "manufacturing": 78,
        "logistics": 80,
        "labor": 82,
        "warehouse": 80,
        "growth": 80,
        "automotive": 68,
        "warehousing": 78,
        "food_manufacturing": 60,
        "battery_manufacturing": 56,
        "semiconductors": 28,
        "distribution_centers": 78,
        "materials_handling": 60,
        "tagline": "Midlands SC — between the port, the Upstate, and I-20.",
        "highlights": [
            "I-20/I-26/I-77 access to Charleston and Charlotte",
            "Auto suppliers and distribution for the state capital",
            "Lower cost than Charleston and Greenville",
        ],
    },
    {
        "cbsa": "26980",
        "short": "Iowa City / Cedar Rapids",
        "name": "Cedar Rapids, IA",
        "state": "IA",
        "region": "Midwest",
        "lat": 41.9779,
        "lon": -91.6656,
        "population": 276_000,
        "manufacturing": 80,
        "logistics": 76,
        "labor": 85,
        "warehouse": 74,
        "growth": 74,
        "automotive": 24,
        "warehousing": 70,
        "food_manufacturing": 91,
        "battery_manufacturing": 26,
        "semiconductors": 22,
        "distribution_centers": 68,
        "materials_handling": 44,
        "tagline": "Cereal, corn processing, and a high-skill Iowa labor shed.",
        "highlights": [
            "Quaker, Cargill, and grain processing",
            "I-380 between Iowa City and Cedar Rapids",
            "Stable manufacturing participation rates",
        ],
    },
]


def metros_frame():
    """Load the metro panel from SQLite, seeding the DB on first run."""
    from .db import load_metros_frame

    return load_metros_frame()
