"""Census 2017/2022 NAICS titles for codes present in SQLite companies.

Generated from unique NAICS in data/moi.sqlite plus Census 2017 and 2022
NAICS structure files (2017 titles win on duplicate codes because TRI/ITA
still report 2017 codes such as 336111).
Unknown codes render as 'NAICS {code}' at runtime.
"""

from __future__ import annotations

NAICS_TITLES: dict[str, str] = {
    '11': 'Agriculture, forestry, fishing and hunting',
    '111': 'Crop production',
    '1114': 'Greenhouse, nursery, and floriculture production',
    '11142': 'Nursery and floriculture production',
    '111422': 'Floriculture production',
    '112': 'Animal production and aquaculture',
    '1125': 'Aquaculture',
    '11251': 'Aquaculture',
    '112511': 'Finfish farming and fish hatcheries',
    '115': 'Support activities for agriculture and forestry',
    '1152': 'Support activities for animal production',
    '11521': 'Support activities for animal production',
    '115210': 'Support activities for animal production',
    '22': 'Utilities',
    '221': 'Utilities',
    '2211': 'Electric power generation, transmission and distribution',
    '22112': 'Electric power transmission, control, and distribution',
    '221121': 'Electric bulk power transmission and control',
    '221122': 'Electric power distribution',
    '23': 'Construction',
    '236': 'Construction of buildings',
    '2362': 'Nonresidential building construction',
    '23622': 'Commercial and institutional building construction',
    '236220': 'Commercial and institutional building construction',
    '238': 'Specialty trade contractors',
    '2382': 'Building equipment contractors',
    '23822': 'Plumbing, heating, and air-conditioning contractors',
    '238220': 'Plumbing, heating, and air-conditioning contractors',
    '311': 'Food manufacturing',
    '3111': 'Animal food manufacturing',
    '31111': 'Animal food manufacturing',
    '311111': 'Dog and cat food manufacturing',
    '311119': 'Other animal food manufacturing',
    '3112': 'Grain and oilseed milling',
    '31121': 'Flour milling and malt manufacturing',
    '311211': 'Flour milling',
    '311212': 'Rice milling',
    '311213': 'Malt manufacturing',
    '31122': 'Starch and vegetable fats and oils manufacturing',
    '311221': 'Wet corn milling',
    '311224': 'Soybean and other oilseed processing',
    '311225': 'Fats and oils refining and blending',
    '31123': 'Breakfast cereal manufacturing',
    '311230': 'Breakfast cereal manufacturing',
    '3113': 'Sugar and confectionery product manufacturing',
    '31131': 'Sugar manufacturing',
    '311313': 'Beet sugar manufacturing',
    '311314': 'Cane sugar manufacturing',
    '31134': 'Nonchocolate confectionery manufacturing',
    '311340': 'Nonchocolate confectionery manufacturing',
    '31135': 'Chocolate and confectionery manufacturing',
    '311351': 'Chocolate and confectionery manufacturing from cacao beans',
    '311352': 'Confectionery manufacturing from purchased chocolate',
    '3114': 'Fruit and vegetable preserving and specialty food manufacturing',
    '31141': 'Frozen food manufacturing',
    '311411': 'Frozen fruit, juice, and vegetable manufacturing',
    '311412': 'Frozen specialty food manufacturing',
    '31142': 'Fruit and vegetable canning, pickling, and drying',
    '311421': 'Fruit and vegetable canning',
    '311422': 'Specialty canning',
    '311423': 'Dried and dehydrated food manufacturing',
    '3115': 'Dairy product manufacturing',
    '31151': 'Dairy product (except frozen) manufacturing',
    '311510': 'Dairy product (except frozen) manufacturing',
    '311511': 'Fluid milk manufacturing',
    '311512': 'Creamery butter manufacturing',
    '311513': 'Cheese manufacturing',
    '311514': 'Dry, condensed, and evaporated dairy product manufacturing',
    '31152': 'Ice cream and frozen dessert manufacturing',
    '311520': 'Ice cream and frozen dessert manufacturing',
    '3116': 'Animal slaughtering and processing',
    '31161': 'Animal slaughtering and processing',
    '311611': 'Animal (except poultry) slaughtering',
    '311612': 'Meat processed from carcasses',
    '311613': 'Rendering and meat byproduct processing',
    '311615': 'Poultry processing',
    '3117': 'Seafood product preparation and packaging',
    '31171': 'Seafood product preparation and packaging',
    '311710': 'Seafood product preparation and packaging',
    '3118': 'Bakeries and tortilla manufacturing',
    '31181': 'Bread and bakery product manufacturing',
    '311811': 'Retail bakeries',
    '311812': 'Commercial bakeries',
    '311813': 'Frozen cakes, pies, and other pastries manufacturing',
    '31182': 'Cookie, cracker, and pasta manufacturing',
    '311821': 'Cookie and cracker manufacturing',
    '311824': 'Dry pasta, dough, and flour mixes manufacturing from purchased flour',
    '31183': 'Tortilla manufacturing',
    '311830': 'Tortilla manufacturing',
    '3119': 'Other food manufacturing',
    '31191': 'Snack food manufacturing',
    '311911': 'Roasted nuts and peanut butter manufacturing',
    '311919': 'Other snack food manufacturing',
    '31192': 'Coffee and tea manufacturing',
    '311920': 'Coffee and tea manufacturing',
    '31193': 'Flavoring syrup and concentrate manufacturing',
    '311930': 'Flavoring syrup and concentrate manufacturing',
    '31194': 'Seasoning and dressing manufacturing',
    '311941': 'Mayonnaise, dressing, and other prepared sauce manufacturing',
    '311942': 'Spice and extract manufacturing',
    '31199': 'All other food manufacturing',
    '311991': 'Perishable prepared food manufacturing',
    '311999': 'All other miscellaneous food manufacturing',
    '312': 'Beverage and tobacco product manufacturing',
    '3121': 'Beverage manufacturing',
    '31211': 'Soft drink and ice manufacturing',
    '312111': 'Soft drink manufacturing',
    '312112': 'Bottled water manufacturing',
    '312113': 'Ice manufacturing',
    '31212': 'Breweries',
    '312120': 'Breweries',
    '31213': 'Wineries',
    '312130': 'Wineries',
    '31214': 'Distilleries',
    '312140': 'Distilleries',
    '315': 'Apparel manufacturing',
    '3152': 'Cut and sew apparel manufacturing',
    '31522': 'Men’s and boys’ cut and sew apparel manufacturing',
    '315220': 'Men’s and boys’ cut and sew apparel manufacturing',
    '31525': 'Cut and sew apparel manufacturing (except contractors)',
    '315250': 'Cut and sew apparel manufacturing (except contractors)',
    '321': 'Wood product manufacturing',
    '3219': 'Other wood product manufacturing',
    '32191': 'Millwork',
    '321911': 'Wood window and door manufacturing',
    '322': 'Paper manufacturing',
    '3221': 'Pulp, paper, and paperboard mills',
    '32212': 'Paper mills',
    '322120': 'Paper mills',
    '3222': 'Converted paper product manufacturing',
    '32221': 'Paperboard container manufacturing',
    '322211': 'Corrugated and solid fiber box manufacturing',
    '322212': 'Folding paperboard box manufacturing',
    '32229': 'Other converted paper product manufacturing',
    '322299': 'All other converted paper product manufacturing',
    '323': 'Printing and related support activities',
    '3231': 'Printing and related support activities',
    '32311': 'Printing',
    '323111': 'Commercial printing (except screen and books)',
    '323113': 'Commercial screen printing',
    '324': 'Petroleum and coal products manufacturing',
    '3241': 'Petroleum and coal products manufacturing',
    '32419': 'Other petroleum and coal products manufacturing',
    '324199': 'All other petroleum and coal products manufacturing',
    '325': 'Chemical manufacturing',
    '3253': 'Pesticide, fertilizer, and other agricultural chemical manufacturing',
    '32532': 'Pesticide and other agricultural chemical manufacturing',
    '325320': 'Pesticide and other agricultural chemical manufacturing',
    '3254': 'Pharmaceutical and medicine manufacturing',
    '32541': 'Pharmaceutical and medicine manufacturing',
    '325411': 'Medicinal and botanical manufacturing',
    '3255': 'Paint, coating, and adhesive manufacturing',
    '32552': 'Adhesive manufacturing',
    '325520': 'Adhesive manufacturing',
    '3256': 'Soap, cleaning compound, and toilet preparation manufacturing',
    '32561': 'Soap and cleaning compound manufacturing',
    '325611': 'Soap and other detergent manufacturing',
    '32562': 'Toilet preparation manufacturing',
    '325620': 'Toilet preparation manufacturing',
    '3259': 'Other chemical product and preparation manufacturing',
    '32599': 'All other chemical product and preparation manufacturing',
    '325998': 'All other miscellaneous chemical product and preparation manufacturing',
    '326': 'Plastics and rubber products manufacturing',
    '3261': 'Plastics product manufacturing',
    '32611': 'Plastics packaging materials and unlaminated film and sheet manufacturing',
    '326111': 'Plastics bag and pouch manufacturing',
    '32612': 'Plastics pipe, pipe fitting, and unlaminated profile shape manufacturing',
    '326122': 'Plastics pipe and pipe fitting manufacturing',
    '32614': 'Polystyrene foam product manufacturing',
    '326140': 'Polystyrene foam product manufacturing',
    '32619': 'Other plastics product manufacturing',
    '326199': 'All other plastics product manufacturing',
    '327': 'Nonmetallic mineral product manufacturing',
    '3272': 'Glass and glass product manufacturing',
    '32721': 'Glass and glass product manufacturing',
    '327212': 'Other pressed and blown glass and glassware manufacturing',
    '3273': 'Cement and concrete product manufacturing',
    '32732': 'Ready-mix concrete manufacturing',
    '327320': 'Ready-mix concrete manufacturing',
    '3279': 'Other nonmetallic mineral product manufacturing',
    '32799': 'All other nonmetallic mineral product manufacturing',
    '327991': 'Cut stone and stone product manufacturing',
    '331': 'Primary metal manufacturing',
    '3312': 'Steel product manufacturing from purchased steel',
    '33121': 'Iron and steel pipe and tube manufacturing from purchased steel',
    '331210': 'Iron and steel pipe and tube manufacturing from purchased steel',
    '33122': 'Rolling and drawing of purchased steel',
    '331221': 'Rolled steel shape manufacturing',
    '3314': 'Nonferrous metal (except aluminum) production and processing',
    '33142': 'Copper rolling, drawing, extruding, and alloying',
    '331420': 'Copper rolling, drawing, extruding, and alloying',
    '33149': 'Nonferrous metal (except copper and aluminum) rolling, drawing, extruding, and alloying',
    '331492': 'Secondary smelting, refining, and alloying of nonferrous metal (except copper and aluminum)',
    '3315': 'Foundries',
    '33151': 'Ferrous metal foundries',
    '331511': 'Iron foundries',
    '332': 'Fabricated metal product manufacturing',
    '3322': 'Cutlery and handtool manufacturing',
    '33221': 'Cutlery and handtool manufacturing',
    '332216': 'Saw blade and handtool manufacturing',
    '3323': 'Architectural and structural metals manufacturing',
    '33231': 'Plate work and fabricated structural product manufacturing',
    '332312': 'Fabricated structural metal manufacturing',
    '33232': 'Ornamental and architectural metal products manufacturing',
    '332321': 'Metal window and door manufacturing',
    '332322': 'Sheet metal work manufacturing',
    '3324': 'Boiler, tank, and shipping container manufacturing',
    '33242': 'Metal tank (heavy gauge) manufacturing',
    '332420': 'Metal tank (heavy gauge) manufacturing',
    '33243': 'Metal can, box, and other metal container (light gauge) manufacturing',
    '332431': 'Metal can manufacturing',
    '332439': 'Other metal container manufacturing',
    '3325': 'Hardware manufacturing',
    '33251': 'Hardware manufacturing',
    '332510': 'Hardware manufacturing',
    '3326': 'Spring and wire product manufacturing',
    '33261': 'Spring and wire product manufacturing',
    '332618': 'Other fabricated wire product manufacturing',
    '3329': 'Other fabricated metal product manufacturing',
    '33291': 'Metal valve manufacturing',
    '332919': 'Other metal valve and pipe fitting manufacturing',
    '33299': 'All other fabricated metal product manufacturing',
    '332991': 'Ball and roller bearing manufacturing',
    '332999': 'All other miscellaneous fabricated metal product manufacturing',
    '333': 'Machinery manufacturing',
    '3331': 'Agriculture, construction, and mining machinery manufacturing',
    '33311': 'Agricultural implement manufacturing',
    '333111': 'Farm machinery and equipment manufacturing',
    '33313': 'Mining and oil and gas field machinery manufacturing',
    '333131': 'Mining machinery and equipment manufacturing',
    '333132': 'Oil and gas field machinery and equipment manufacturing',
    '3334': 'Ventilation, heating, air-conditioning, and commercial refrigeration equipment manufacturing',
    '33341': 'Ventilation, heating, air-conditioning, and commercial refrigeration equipment manufacturing',
    '333413': 'Industrial and commercial fan and blower and air purification equipment manufacturing',
    '333414': 'Heating equipment (except warm air furnaces) manufacturing',
    '333415': 'Air-conditioning and warm air heating equipment and commercial and industrial refrigeration equipment manufacturing',
    '3335': 'Metalworking machinery manufacturing',
    '33351': 'Metalworking machinery manufacturing',
    '333515': 'Cutting tool and machine tool accessory manufacturing',
    '3339': 'Other general purpose machinery manufacturing',
    '33391': 'Pump and compressor manufacturing',
    '333912': 'Air and gas compressor manufacturing',
    '33392': 'Material handling equipment manufacturing',
    '333921': 'Elevator and moving stairway manufacturing',
    '333922': 'Conveyor and conveying equipment manufacturing',
    '333923': 'Overhead traveling crane, hoist, and monorail system manufacturing',
    '333924': 'Industrial truck, tractor, trailer, and stacker machinery manufacturing',
    '334': 'Computer and electronic product manufacturing',
    '3344': 'Semiconductor and other electronic component manufacturing',
    '33441': 'Semiconductor and other electronic component manufacturing',
    '334412': 'Bare printed circuit board manufacturing',
    '334413': 'Semiconductor and related device manufacturing',
    '334416': 'Capacitor, resistor, coil, transformer, and other inductor manufacturing',
    '334417': 'Electronic connector manufacturing',
    '334418': 'Printed circuit assembly (electronic assembly) manufacturing',
    '334419': 'Other electronic component manufacturing',
    '335': 'Electrical equipment, appliance, and component manufacturing',
    '3359': 'Other electrical equipment and component manufacturing',
    '33591': 'Battery manufacturing',
    '335910': 'Battery manufacturing',
    '335911': 'Storage battery manufacturing',
    '335912': 'Primary battery manufacturing',
    '33592': 'Communication and energy wire and cable manufacturing',
    '335929': 'Other communication and energy wire manufacturing',
    '33599': 'All other electrical equipment and component manufacturing',
    '335991': 'Carbon and graphite product manufacturing',
    '335999': 'All other miscellaneous electrical equipment and component manufacturing',
    '336': 'Transportation equipment manufacturing',
    '3361': 'Motor vehicle manufacturing',
    '33611': 'Automobile and light duty motor vehicle manufacturing',
    '336110': 'Automobile and light duty motor vehicle manufacturing',
    '336111': 'Automobile manufacturing',
    '336112': 'Light truck and utility vehicle manufacturing',
    '33612': 'Heavy duty truck manufacturing',
    '336120': 'Heavy duty truck manufacturing',
    '3362': 'Motor vehicle body and trailer manufacturing',
    '33621': 'Motor vehicle body and trailer manufacturing',
    '336210': 'Motor vehicle body and trailer manufacturing',
    '336211': 'Motor vehicle body manufacturing',
    '336212': 'Truck trailer manufacturing',
    '336213': 'Motor home manufacturing',
    '336214': 'Travel trailer and camper manufacturing',
    '3363': 'Motor vehicle parts manufacturing',
    '33631': 'Motor vehicle gasoline engine and engine parts manufacturing',
    '336310': 'Motor vehicle gasoline engine and engine parts manufacturing',
    '336312': 'Motor vehicle gasoline engine and engine parts manufacturing',
    '33632': 'Motor vehicle electrical and electronic equipment manufacturing',
    '336320': 'Motor vehicle electrical and electronic equipment manufacturing',
    '33633': 'Motor vehicle steering and suspension components (except spring) manufacturing',
    '336330': 'Motor vehicle steering and suspension components (except spring) manufacturing',
    '33634': 'Motor vehicle brake system manufacturing',
    '336340': 'Motor vehicle brake system manufacturing',
    '33635': 'Motor vehicle transmission and power train parts manufacturing',
    '336350': 'Motor vehicle transmission and power train parts manufacturing',
    '33636': 'Motor vehicle seating and interior trim manufacturing',
    '336360': 'Motor vehicle seating and interior trim manufacturing',
    '33637': 'Motor vehicle metal stamping',
    '336370': 'Motor vehicle metal stamping',
    '33639': 'Other motor vehicle parts manufacturing',
    '336390': 'Other motor vehicle parts manufacturing',
    '3369': 'Other transportation equipment manufacturing',
    '33699': 'Other transportation equipment manufacturing',
    '336999': 'All other transportation equipment manufacturing',
    '337': 'Furniture and related product manufacturing',
    '3372': 'Office furniture (including fixtures) manufacturing',
    '33721': 'Office furniture (including fixtures) manufacturing',
    '337214': 'Office furniture (except wood) manufacturing',
    '337215': 'Showcase, partition, shelving, and locker manufacturing',
    '3379': 'Other furniture related product manufacturing',
    '33791': 'Mattress manufacturing',
    '337910': 'Mattress manufacturing',
    '339': 'Miscellaneous manufacturing',
    '3391': 'Medical equipment and supplies manufacturing',
    '33911': 'Medical equipment and supplies manufacturing',
    '339112': 'Surgical and medical instrument manufacturing',
    '3399': 'Other miscellaneous manufacturing',
    '33992': 'Sporting and athletic goods manufacturing',
    '339920': 'Sporting and athletic goods manufacturing',
    '33993': 'Doll, toy, and game manufacturing',
    '339930': 'Doll, toy, and game manufacturing',
    '33994': 'Office supplies (except paper) manufacturing',
    '339940': 'Office supplies (except paper) manufacturing',
    '33995': 'Sign manufacturing',
    '339950': 'Sign manufacturing',
    '42': 'Wholesale trade',
    '423': 'Merchant wholesalers, durable goods',
    '4231': 'Motor vehicle and motor vehicle parts and supplies merchant wholesalers',
    '42312': 'Motor vehicle supplies and new parts merchant wholesalers',
    '423120': 'Motor vehicle supplies and new parts merchant wholesalers',
    '4233': 'Lumber and other construction materials merchant wholesalers',
    '42331': 'Lumber, plywood, millwork, and wood panel merchant wholesalers',
    '423310': 'Lumber, plywood, millwork, and wood panel merchant wholesalers',
    '42339': 'Other construction material merchant wholesalers',
    '423390': 'Other construction material merchant wholesalers',
    '4234': 'Professional and commercial equipment and supplies merchant wholesalers',
    '42342': 'Office equipment merchant wholesalers',
    '423420': 'Office equipment merchant wholesalers',
    '42344': 'Other commercial equipment merchant wholesalers',
    '423440': 'Other commercial equipment merchant wholesalers',
    '42345': 'Medical, dental, and hospital equipment and supplies merchant wholesalers',
    '423450': 'Medical, dental, and hospital equipment and supplies merchant wholesalers',
    '42346': 'Ophthalmic goods merchant wholesalers',
    '423460': 'Ophthalmic goods merchant wholesalers',
    '4235': 'Metal and mineral (except petroleum) merchant wholesalers',
    '42351': 'Metal service centers and other metal merchant wholesalers',
    '423510': 'Metal service centers and other metal merchant wholesalers',
    '4236': 'Household appliances and electrical and electronic goods merchant wholesalers',
    '42361': 'Electrical apparatus and equipment, wiring supplies, and related equipment merchant wholesalers',
    '423610': 'Electrical apparatus and equipment, wiring supplies, and related equipment merchant wholesalers',
    '42369': 'Other electronic parts and equipment merchant wholesalers',
    '423690': 'Other electronic parts and equipment merchant wholesalers',
    '4237': 'Hardware, and plumbing and heating equipment and supplies merchant wholesalers',
    '42371': 'Hardware merchant wholesalers',
    '423710': 'Hardware merchant wholesalers',
    '42372': 'Plumbing and heating equipment and supplies (hydronics) merchant wholesalers',
    '423720': 'Plumbing and heating equipment and supplies (hydronics) merchant wholesalers',
    '42373': 'Warm air heating and air-conditioning equipment and supplies merchant wholesalers',
    '423730': 'Warm air heating and air-conditioning equipment and supplies merchant wholesalers',
    '4238': 'Machinery, equipment, and supplies merchant wholesalers',
    '42381': 'Construction and mining (except oil well) machinery and equipment merchant wholesalers',
    '423810': 'Construction and mining (except oil well) machinery and equipment merchant wholesalers',
    '42382': 'Farm and garden machinery and equipment merchant wholesalers',
    '423820': 'Farm and garden machinery and equipment merchant wholesalers',
    '42384': 'Industrial supplies merchant wholesalers',
    '423840': 'Industrial supplies merchant wholesalers',
    '42385': 'Service establishment equipment and supplies merchant wholesalers',
    '423850': 'Service establishment equipment and supplies merchant wholesalers',
    '42386': 'Transportation equipment and supplies (except motor vehicle) merchant wholesalers',
    '423860': 'Transportation equipment and supplies (except motor vehicle) merchant wholesalers',
    '4239': 'Miscellaneous durable goods merchant wholesalers',
    '42391': 'Sporting and recreational goods and supplies merchant wholesalers',
    '423910': 'Sporting and recreational goods and supplies merchant wholesalers',
    '42392': 'Toy and hobby goods and supplies merchant wholesalers',
    '423920': 'Toy and hobby goods and supplies merchant wholesalers',
    '42399': 'Other miscellaneous durable goods merchant wholesalers',
    '423990': 'Other miscellaneous durable goods merchant wholesalers',
    '424': 'Merchant wholesalers, nondurable goods',
    '4242': "Drugs and druggists' sundries merchant wholesalers",
    '42421': "Drugs and druggists' sundries merchant wholesalers",
    '424210': "Drugs and druggists' sundries merchant wholesalers",
    '4243': 'Apparel, piece goods, and notions merchant wholesalers',
    '42431': 'Piece goods, notions, and other dry goods merchant wholesalers',
    '424310': 'Piece goods, notions, and other dry goods merchant wholesalers',
    '42432': "Men's and boys' clothing and furnishings merchant wholesalers",
    '424320': "Men's and boys' clothing and furnishings merchant wholesalers",
    '42434': 'Footwear merchant wholesalers',
    '424340': 'Footwear merchant wholesalers',
    '4244': 'Grocery and related product merchant wholesalers',
    '42441': 'General line grocery merchant wholesalers',
    '424410': 'General line grocery merchant wholesalers',
    '42443': 'Dairy product (except dried or canned) merchant wholesalers',
    '424430': 'Dairy product (except dried or canned) merchant wholesalers',
    '42447': 'Meat and meat product merchant wholesalers',
    '424470': 'Meat and meat product merchant wholesalers',
    '42448': 'Fresh fruit and vegetable merchant wholesalers',
    '424480': 'Fresh fruit and vegetable merchant wholesalers',
    '42449': 'Other grocery and related products merchant wholesalers',
    '424490': 'Other grocery and related products merchant wholesalers',
    '4245': 'Farm product raw material merchant wholesalers',
    '42459': 'Other farm product raw material merchant wholesalers',
    '424590': 'Other farm product raw material merchant wholesalers',
    '4246': 'Chemical and allied products merchant wholesalers',
    '42469': 'Other chemical and allied products merchant wholesalers',
    '424690': 'Other chemical and allied products merchant wholesalers',
    '4247': 'Petroleum and petroleum products merchant wholesalers',
    '42471': 'Petroleum bulk stations and terminals',
    '424710': 'Petroleum bulk stations and terminals',
    '42472': 'Petroleum and petroleum products merchant wholesalers (except bulk stations and terminals)',
    '424720': 'Petroleum and petroleum products merchant wholesalers (except bulk stations and terminals)',
    '4248': 'Beer, wine, and distilled alcoholic beverage merchant wholesalers',
    '42481': 'Beer and ale merchant wholesalers',
    '424810': 'Beer and ale merchant wholesalers',
    '42482': 'Wine and distilled alcoholic beverage merchant wholesalers',
    '424820': 'Wine and distilled alcoholic beverage merchant wholesalers',
    '4249': 'Miscellaneous nondurable goods merchant wholesalers',
    '42492': 'Book, periodical, and newspaper merchant wholesalers',
    '424920': 'Book, periodical, and newspaper merchant wholesalers',
    '42495': 'Paint, varnish, and supplies merchant wholesalers',
    '424950': 'Paint, varnish, and supplies merchant wholesalers',
    '42499': 'Other miscellaneous nondurable goods merchant wholesalers',
    '424990': 'Other miscellaneous nondurable goods merchant wholesalers',
    '441': 'Motor vehicle and parts dealers',
    '4413': 'Automotive parts, accessories, and tire stores',
    '44131': 'Automotive parts and accessories stores',
    '441310': 'Automotive parts and accessories stores',
    '44132': 'Tire dealers',
    '441320': 'Tire dealers',
    '442': 'Furniture and home furnishings stores',
    '4421': 'Furniture stores',
    '44211': 'Furniture stores',
    '442110': 'Furniture stores',
    '4422': 'Home furnishings stores',
    '44229': 'Other home furnishings stores',
    '442299': 'All other home furnishings stores',
    '444': 'Building material and garden equipment and supplies dealers',
    '4441': 'Building material and supplies dealers',
    '44411': 'Home centers',
    '444110': 'Home centers',
    '44413': 'Hardware stores',
    '444130': 'Hardware stores',
    '44414': 'Hardware retailers',
    '444140': 'Hardware retailers',
    '44419': 'Other building material dealers',
    '444190': 'Other building material dealers',
    '4442': 'Lawn and garden equipment and supplies stores',
    '44422': 'Nursery, garden center, and farm supply stores',
    '444220': 'Nursery, garden center, and farm supply stores',
    '44424': 'Nursery, garden center, and farm supply retailers',
    '444240': 'Nursery, garden center, and farm supply retailers',
    '445': 'Food and beverage stores',
    '4451': 'Grocery stores',
    '44511': 'Supermarkets and other grocery (except convenience) stores',
    '445110': 'Supermarkets and other grocery (except convenience) stores',
    '44513': 'Convenience retailers and vending machine operators',
    '445131': 'Convenience retailers',
    '4453': 'Beer, wine, and liquor stores',
    '44531': 'Beer, wine, and liquor stores',
    '445310': 'Beer, wine, and liquor stores',
    '446': 'Health and personal care stores',
    '4461': 'Health and personal care stores',
    '44612': 'Cosmetics, beauty supplies, and perfume stores',
    '446120': 'Cosmetics, beauty supplies, and perfume stores',
    '447': 'Gasoline stations',
    '4471': 'Gasoline stations',
    '44711': 'Gasoline stations with convenience stores',
    '447110': 'Gasoline stations with convenience stores',
    '449': 'Furniture, home furnishings, electronics, and appliance retailers',
    '4491': 'Furniture and home furnishings retailers',
    '44911': 'Furniture retailers',
    '449110': 'Furniture retailers',
    '4492': 'Electronics and appliance retailers',
    '44921': 'Electronics and appliance retailers',
    '449210': 'Electronics and appliance retailers',
    '451': 'Sporting goods, hobby, musical instrument, and book stores',
    '4511': 'Sporting goods, hobby, and musical instrument stores',
    '45111': 'Sporting goods stores',
    '451110': 'Sporting goods stores',
    '452': 'General merchandise stores',
    '452112': 'General merchandise stores',
    '4523': 'General merchandise stores, including warehouse clubs and supercenters',
    '45231': 'General merchandise stores, including warehouse clubs and supercenters',
    '452311': 'Warehouse clubs and supercenters',
    '452319': 'All other general merchandise stores',
    '452910': 'General merchandise stores',
    '452990': 'General merchandise stores',
    '453': 'Miscellaneous store retailers',
    '4533': 'Used merchandise stores',
    '45331': 'Used merchandise stores',
    '453310': 'Used merchandise stores',
    '454': 'Nonstore retailers',
    '4541': 'Electronic shopping and mail-order houses',
    '45411': 'Electronic shopping and mail-order houses',
    '454110': 'Electronic shopping and mail-order houses',
    '454111': 'Electronic shopping and mail-order houses',
    '454113': 'Electronic shopping and mail-order houses',
    '455': 'General merchandise retailers',
    '4552': 'Warehouse clubs, supercenters, and other general merchandise retailers',
    '45521': 'Warehouse clubs, supercenters, and other general merchandise retailers',
    '455219': 'All other general merchandise retailers',
    '456': 'Health and personal care retailers',
    '4561': 'Health and personal care retailers',
    '45611': 'Pharmacies and drug retailers',
    '456110': 'Pharmacies and drug retailers',
    '484': 'Truck transportation',
    '4841': 'General freight trucking',
    '48411': 'General freight trucking, local',
    '484110': 'General freight trucking, local',
    '48412': 'General freight trucking, long-distance',
    '484121': 'General freight trucking, long-distance, truckload',
    '484122': 'General freight trucking, long-distance, less than truckload',
    '488': 'Support activities for transportation',
    '4881': 'Support activities for air transportation',
    '48819': 'Other support activities for air transportation',
    '488190': 'Other support activities for air transportation',
    '4885': 'Freight transportation arrangement',
    '48851': 'Freight transportation arrangement',
    '488510': 'Freight transportation arrangement',
    '4889': 'Other support activities for transportation',
    '48899': 'Other support activities for transportation',
    '488991': 'Packing and crating',
    '492': 'Couriers and messengers',
    '4921': 'Couriers and express delivery services',
    '49211': 'Couriers and express delivery services',
    '492110': 'Couriers and express delivery services',
    '4922': 'Local messengers and local delivery',
    '49221': 'Local messengers and local delivery',
    '492210': 'Local messengers and local delivery',
    '493': 'Warehousing and storage',
    '4931': 'Warehousing and storage',
    '493100': 'Warehousing and storage',
    '49311': 'General warehousing and storage',
    '493110': 'General warehousing and storage',
    '493111': 'General warehousing and storage',
    '49312': 'Refrigerated warehousing and storage',
    '493120': 'Refrigerated warehousing and storage',
    '49313': 'Farm product warehousing and storage',
    '493130': 'Farm product warehousing and storage',
    '49319': 'Other warehousing and storage',
    '493190': 'Other warehousing and storage',
    '51': 'Information',
    '511': 'Publishing industries (except internet)',
    '5111': 'Newspaper, periodical, book, and directory publishers',
    '51113': 'Book publishers',
    '511130': 'Book publishers',
    '517': 'Telecommunications',
    '5171': 'Wired and wireless telecommunications (except satellite)',
    '51711': 'Wired and wireless telecommunications carriers (except satellite)',
    '517110': 'Wired and wireless telecommunications carriers (except satellite)',
    '53': 'Real estate and rental and leasing',
    '531': 'Real estate',
    '5311': 'Lessors of real estate',
    '53112': 'Lessors of nonresidential buildings (except miniwarehouses)',
    '531120': 'Lessors of nonresidential buildings (except miniwarehouses)',
    '54': 'Professional, scientific, and technical services',
    '541': 'Professional, scientific, and technical services',
    '5412': 'Accounting, tax preparation, bookkeeping, and payroll services',
    '54121': 'Accounting, tax preparation, bookkeeping, and payroll services',
    '541219': 'Other accounting services',
    '5417': 'Scientific research and development services',
    '54171': 'Research and development in the physical, engineering, and life sciences',
    '541714': 'Research and development in biotechnology (except nanobiotechnology)',
    '55': 'Management of companies and enterprises',
    '551': 'Management of companies and enterprises',
    '5511': 'Management of companies and enterprises',
    '55111': 'Management of companies and enterprises',
    '551114': 'Corporate, subsidiary, and regional managing offices',
    '56': 'Administrative and support and waste management and remediation services',
    '561': 'Administrative and support services',
    '5612': 'Facilities support services',
    '56121': 'Facilities support services',
    '561210': 'Facilities support services',
    '5617': 'Services to buildings and dwellings',
    '56172': 'Janitorial services',
    '561720': 'Janitorial services',
    '61': 'Educational services',
    '611': 'Educational services',
    '6113': 'Colleges, universities, and professional schools',
    '61131': 'Colleges, universities, and professional schools',
    '611310': 'Colleges, universities, and professional schools',
    '62': 'Health care and social assistance',
    '621': 'Ambulatory health care services',
    '6215': 'Medical and diagnostic laboratories',
    '62151': 'Medical and diagnostic laboratories',
    '621511': 'Medical laboratories',
    '622': 'Hospitals',
    '6221': 'General medical and surgical hospitals',
    '62211': 'General medical and surgical hospitals',
    '622110': 'General medical and surgical hospitals',
    '624': 'Social assistance',
    '6241': 'Individual and family services',
    '62412': 'Services for the elderly and persons with disabilities',
    '624120': 'Services for the elderly and persons with disabilities',
    '6242': 'Community food and housing, and emergency and other relief services',
    '62421': 'Community food services',
    '624210': 'Community food services',
    '62422': 'Community housing services',
    '624221': 'Temporary shelters',
    '6243': 'Vocational rehabilitation services',
    '62431': 'Vocational rehabilitation services',
    '624310': 'Vocational rehabilitation services',
    '71': 'Arts, entertainment, and recreation',
    '713': 'Amusement, gambling, and recreation industries',
    '7132': 'Gambling industries',
    '71321': 'Casinos (except casino hotels)',
    '713210': 'Casinos (except casino hotels)',
    '71329': 'Other gambling industries',
    '713290': 'Other gambling industries',
    '72': 'Accommodation and food services',
    '722': 'Food services and drinking places',
    '7223': 'Special food services',
    '72233': 'Mobile food services',
    '722330': 'Mobile food services',
    '81': 'Other services (except public administration)',
    '811': 'Repair and maintenance',
    '8111': 'Automotive repair and maintenance',
    '81112': 'Automotive body, paint, interior, and glass repair',
    '811121': 'Automotive body, paint, and interior repair and maintenance',
    '812': 'Personal and laundry services',
    '8123': 'Drycleaning and laundry services',
    '81233': 'Linen and uniform supply',
    '812331': 'Linen supply',
    '813': 'Religious, grantmaking, civic, professional, and similar organizations',
    '8131': 'Religious organizations',
    '81311': 'Religious organizations',
    '813110': 'Religious organizations',
    '8133': 'Social advocacy organizations',
    '81331': 'Social advocacy organizations',
    '813319': 'Other social advocacy organizations',
    '92': 'Public administration',
    '921': 'Executive, legislative, and other general government support',
    '9211': 'Executive, legislative, and other general government support',
    '92111': 'Executive offices',
    '921110': 'Executive offices',
    '92119': 'Other general government support',
    '921190': 'Other general government support',
}


def naics_title(code: str) -> str | None:
    """Return the Census title for a NAICS code, walking shorter prefixes."""
    digits = "".join(ch for ch in str(code) if ch.isdigit())
    for n in range(len(digits), 1, -1):
        title = NAICS_TITLES.get(digits[:n])
        if title:
            return title
    return None


def format_naics_label(code: str) -> str:
    """Dropdown label: NAICS 336111 — Automobile manufacturing."""
    digits = "".join(ch for ch in str(code) if ch.isdigit())
    title = naics_title(digits)
    if not title:
        return f"NAICS {digits}"
    return f"NAICS {digits} — {title}"
